### ISSUE TITLE
Make configuration less verbose

### ISSUE THREAD

**Issue by tersmitten** [Oefenweb/ansible-bash#2]
``` yaml
bash_bashrc_destinations:
  skell:
    dest: /etc/skel
  current:
    dest: "{{ ansible_env.HOME }}"
  mtersmitten:
    dest: /home/mtersmitten
    owner: mtersmitten
    group: mtersmitten
```

There should be no need to specify `group` when it's the same as `owner`.
