### ISSUE TITLE
Question about Ansible-bash

### ISSUE THREAD

**Issue by bong101** [Oefenweb/ansible-bash#4]
Hi, 
I'm tring to use your ansible-playbook. It works very well for root, very nice prompt, etc...
But how to use it for all users, or for list of users?

Thanks in advance
Olivier

**Comment by tersmitten** [comment]
This is how I use it

```yaml
# bash role variables
---
bash_bashrc_destinations:
  skell:
    dest: /etc/skel
  current:
    dest: "{{ ansible_env.HOME }}"
  mtersmitten:
    dest: /home/mtersmitten
    owner: mtersmitten

bashrc_lines:
  - |
    if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
      export WORKON_HOME=$HOME/.virtualenvs
      export PROJECT_HOME=$HOME/checkouts
      . /usr/local/bin/virtualenvwrapper.sh
    fi

    PACKER_VERSION="${PACKER_VERSION:-1.3.4}"
    export PATH=$PATH:/opt/packer-${PACKER_VERSION}
    export PACKER_CACHE_DIR="${HOME}/.cache/packer"

    GOPATH="${HOME}/go:/opt/go"

    export GPG_TTY=$(tty)

    umask 0022

bash_aliases:
  mkdir: 'mkdir -p'
```
